Repository paris-saclay-cds/ramp-board, pull requests merged in 2020-10, with the labels that each got.

#447 BUG Add wait between status checks AWS worker
  doc/create_ramp_event.rst
  doc/workers.rst
  ramp-engine/ramp_engine/aws/worker.py
  ramp-engine/ramp_engine/base.py
  ramp-engine/ramp_engine/cli.py
  ramp-engine/ramp_engine/dispatcher.py
  ramp-utils/ramp_utils/template/ramp_config_template.yml
Labels: bug

#451 DOC Update contributing.rst
  doc/contribute.rst
Labels: hacktoberfest-accepted

#450 ADV/STY Round train/test times to ms in the leaderboard
  ramp-database/ramp_database/tools/leaderboard.py
Labels: adv-backport-candidate
